### ISSUE TITLE
GCOS 2022 Speech Application

### ISSUE THREAD

**Issue by caoqianyun** [nextarch/collaborators#40]
To provide NextArch Foundation collaborators with more communication opportunities and display platforms, we plan to co-sponsors the _GCOS 2022(Global Cloud Native and Open Source Summit)_ .

Now there are a small number of speech opportunities of  sub-session available for NextArch Foundation collaborators. **You are encouraged to apply the speech according to the following information**! 

More Information about the summit：
- **Time**：March 11, 2022
-  **Place**：Shanghai, China
- **Scale**：more than 2,000 developers who focus on cloud native and open source
- **Website**：https://www.bagevent.com/event/7715147?bag_track=bagevent
- **Sub-forum Content**：
  - 云原生架构与容器 Cloud Native Architecture and Container
  - 云原生应用案例 Cloud Native Use Cases
  - 开源应用与治理 Open Source Applications and Governance

After you apply for the topics, the committee of the summit will review the topics as soon as possible and decide whether to pass or not.

You could comment **in Chinese**(is best, English for overseas speech person) in this issue according to the following template. **This issue will open until all topics of the summit have been solicited. It's better to apply as soon as possible. **

## Template:
- Speech Person Name：
- Speech Person Title：
- Speech Person Email：
- Topic Name：
- Abstract of the Topic（_less than 200 words_）：

**Comment by yangwenmai** [comment]
![image](https://user-images.githubusercontent.com/1710912/149255594-4a1590b9-deee-4f7c-8aa8-4821fabcb033.png)
GCOS 2022 Time is May 11 or March 11?

**Comment by bertyuan** [comment]
Speech Person Name：袁晓沛
Speech Person Title：高级研发经理
Speech Person Email：bertyuan@icloud.com
Topic Name：混部调度，百度云原生降本增效的密码
Abstract of the Topic（less than 200 words）：据统计，IDC服务器的平均利用率不超过15%，随着IT规模的扩大，资源利用率成为企业降本增效的关键。在云原生之前，各大厂商各有各的方案，但门槛较高，没法普及。随着云原生的发展和K8S的普及，出现了基于K8S的在线业务之间、及在离线业务混合部署的调度器，提供了有可能统一解决资源利用率的终极方案。本talk将分享百度基于K8S构建云原生在线超卖、在离线混部调度器的最佳实践，CPU平均利用率提升至45%以上，并且在线业务不受影响。

**Comment by mlycore** [comment]
- Speech Person Name：苗立尧
- Speech Person Title：SphereEx Cloud Engineer
- Speech Person Email：miaoliyao@sphere-ex.com
- Topic Name：ShardingSphere in the cloud native way
- Abstract of the Topic（less than 200 words）：本次分享将为大家介绍 ShardingSphere 的能力和生态，以及如何通过简单几步将 ShardingSphere Proxy 部署在 Kubernetes 环境中，为开发者和 DBA 提供更加易用、好用的管理体验，最后会分享在云原大潮下，数据库中间件将如何进行解构和适应。

**Comment by fanweixiao** [comment]
- Speech Person Name：C.C. 范维肖
- Speech Person Title：Cofounder of Allegro Networks
- Speech Person Email：[cc@yomo.run](mailto:cc@yomo.run)
- Topic Name：The Next Stage of Edge Computing
- Abstract of the Topic（less than 200 words）：Edge Computing 正在从过去 30 年的 On-premise 架构走向云计算时代，2021 年是 Global Edge Networks 元年，Shopify、Cloudflare 相继发布其 Edge Cloud 产品。Allegro Networks 为下一代边缘计算打造的开源开发框架 YoMo，也被应用在海外的 Metaverse、VR/AR 和国内的 IoT、电动汽车等领域，CC 将会分享下一代边缘计算的架构理念和应用经验。
